name: CI-admin-app

on:
  push:
    branches:
      - 5-jscodeshift
    paths:
      - 'apps/admin/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-install

      #  - name: typecheck web-app
      #   working-directory: apps/admin
      #   run: |
      #     yarn typecheck

      #   - name: jest web-app
      #   working-directory: apps/admin
      #   run: |
      #     yarn jest

      # - name: e2e web-app
      #   working-directory: apps/admin
      #   run: |
      #     yarn cypress

      - name: build web-app
        working-directory: apps/admin
        run: |
          yarn build
